services:
  resume-site:
    build:
      # This tells Dokploy to look in the current directory for the files
      context: . 
      dockerfile: dockerfile
    container_name: nextjs-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always